[build]
    base = "."
    publish = "build"
    command = "REACT_APP_STAGE=staging yarn build"

[context.production]
    command = "REACT_APP_STAGE=production yarn build"

[context.deploy-preview]
    command = "REACT_APP_STAGE=staging yarn build"

[context.branch-deploy]
    command = "REACT_APP_STAGE=staging yarn build"
    
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200