[build]
    base = "."
    publish = "./build"
    command = "yarn build"

[[redirects]]
    from = "/api/*"
    to = "https://career-endorsement-api.herokuapp.com/api/:splat"
    status = 200
    
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200